import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Footer } from "./components/footer/page";
import { Navbar } from "./components/navBar/navbar";
import Providers from "./provider/cartProvider";
import { ProductsProvider } from "../context/productContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full">
			<body
				className={`${geistSans.variable} ${geistMono.variable} relative antialiased h-full`}
			>
				<Providers>
					<ProductsProvider>
						<div className="min-h-screen flex flex-col">
							<Navbar />
							<main className="flex-1">{children}</main>
							<Toaster richColors position="top-right" />
							<Footer />
						</div>
					</ProductsProvider>
				</Providers>
			</body>
		</html>
	);
}
